{{- range .Values.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: svc-{{ .name }}
 labels:
   app: {{ .name }}
spec:
 replicas: {{ .image.replicaCount }}
 selector:
   matchLabels:
       app: {{ .name }}
 template:
   metadata:
     labels:
       app: {{ .name }}
   spec:
     containers:
       - name: name
         image: "{{ .image.repository }}:{{ .image.tag }}"
         imagePullPolicy: IfNotPresent
         ports:
           - name: http
             containerPort: 80
             protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sv-{{ .name }}
  labels:
    app: {{ .name }}
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: {{ .name }}             
{{ end }}