{{- range .Values.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: svc-{{ .name }}
 labels:
   app: {{ $.Values.app.name }}
   version: {{ .name }}
   release: {{ $.Release.Name }}   
spec:
 replicas: {{ .image.replicaCount }}
 selector:
   matchLabels:
       app: {{ $.Values.app.name }}
       version: {{ .name }}
       release: {{ $.Release.Name }}
 template:
   metadata:
     labels:
       app: {{ $.Values.app.name }}
       version: {{ .name }}
       release: {{ $.Release.Name }}
   spec:
     containers:
       - name: name
         image: "{{ .image.repository }}:{{ .image.tag }}"
         imagePullPolicy: IfNotPresent
         ports:
           - name: http
             containerPort: 80
             protocol: TCP
{{ end }}