{{- range .Values.versions }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: svc-{{ .name }}
 labels:
   app: {{ $.Values.app.name }}
   version: {{ .name }}
   release: {{ $.Release.Name }}   
spec:
 replicas: {{ .image.replicaCount }}
 selector:
   matchLabels:
       app: {{ $.Values.app.name }}
       version: {{ .name }}
       release: {{ $.Release.Name }}
 template:
   metadata:
     labels:
       app: {{ $.Values.app.name }}
       version: {{ .name }}
       release: {{ $.Release.Name }}
   spec:
     containers:
       - name: name
         image: "{{ .image.repository }}:{{ .image.tag }}"
         imagePullPolicy: IfNotPresent
         ports:
           - name: http
             containerPort: 80
             protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sv-{{ .name }}
  labels:
    app: {{ $.Values.app.name }}
spec:
  ports:
    - port: 3000
      name: http
  selector:
    app: {{ $.Values.app.name }}             
{{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
{{- range .Values.versions }}  
  - http:
      paths:
      - path: {{.image.prefix}}
        pathType: Prefix
        backend:
          service:
            name: sv-{{ .name }}
            port:
              number: 3000
{{ end }}              
---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: fe-dummy
 labels:
   app: fe-dummy   
spec:
 replicas: 1
 selector:
   matchLabels:
       app: fe-dummy
 template:
   metadata:
     labels:
       app: fe-dummy
   spec:
     containers:
       - name: fe-dummy-container
         image: "docker.io/chetankorat/sample-nodejs-app:v3"
         imagePullPolicy: IfNotPresent
         ports:
           - name: http
             containerPort: 80
             protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: sv-fe-dummy
  labels:
    app: fe-dummy
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
      name: http
  selector:
    app: fe-dummy             
