apiVersion: v1
kind: Service
metadata:
  name: sample-service
  labels:
    app: {{ $.Values.app.name }}
spec:
  type: ClusterIP
  ports:
    - port: 3000
      protocol: TCP
      name: http
  selector:
    app: {{ $.Values.app.name }}